import { StyledNavBar, NavHeading } from "./StyledNavBar";
import {
  Card,
  Card_Image,
  Card_Title,
  Card_Subtitle,
  Flex_Center,
  Music_player_Container,
  Card_Container,
  Music_DetailPage_Container,
  Music_Detail_player_Container,
  Music_Detail_Cover_Backgroud,
  Music_detail_Image,
  Music_detail_Title,
  Music_detail_Subtitle,
  StyledButton,
  Submit_Button,
} from "./StyeledCardMusicList";

import {
  Form_Container,
  StyledInput,
  Validation_Text,
  Form_Label,
  Form_Control,
  Form_Heading,
} from "./StyledForms";
import { Container, Avatar_Image } from "./StyledContainer";
export default StyledNavBar;
export {
  NavHeading,
  Container,
  Card,
  Card_Image,
  Card_Title,
  Card_Subtitle,
  Flex_Center,
  Music_player_Container,
  Card_Container,
  Music_Detail_Cover_Backgroud,
  Music_DetailPage_Container,
  Music_Detail_player_Container,
  Music_detail_Image,
  Music_detail_Title,
  Music_detail_Subtitle,
  StyledButton,
  Submit_Button,
  StyledInput,
  Validation_Text,
  Form_Label,
  Form_Control,
  Form_Container,
  Form_Heading,
  Avatar_Image,
};
